// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trsfgowhqrjijddawhjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyc2Znb3docXJqaWpkZGF3aGp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEzNDE1MTMsImV4cCI6MjA3NjkxNzUxM30.7VKP4j83QyAHHp100_N3Tgy67yW_kd8Fkd8ELpY6Al4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});